apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: orthanc-

labels:
  - pairs:
      app.kubernetes.io/name: orthanc-basic-auth-proxy
      app.kubernetes.io/instance: orthanc-basic-auth-proxy
    includeSelectors: true
    includeTemplates: true

resources:
  - kservice.yaml

configMapGenerator:
  - name: basic-auth-proxy
    files:
      - haproxy.cfg

generatorOptions:
  # Necessary because we are using KNative CRD
  disableNameSuffixHash: true
