apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: orthanc-

labels:
  - pairs:
      app.kubernetes.io/name: orthanc-basic-auth-proxy-again
      app.kubernetes.io/instance: orthanc-basic-auth-proxy-again
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yml
  - service.yml
  - route.yml
