authentik:
  error_reporting:
    enabled: false  # opt-out of anonymous usage data

server:
  resources:
    requests: &REQUESTS
      cpu: 500m
      memory: 2Gi
    limits: *REQUESTS

  ingress:
    enabled: true
    ingressClassName: openshift-default
    annotations:
      cert-manager.io/issuer: letsencrypt
      acme.cert-manager.io/http01-ingress-class: openshift-default
    hosts: &HOSTS
      - auth.blt.chrisproject.org
    tls:
      - secretName: auth-blt-chrisproject-org-letsencrypt
        hosts: *HOSTS

# Doesn't work on NERC-OCP because subchart is hard-coded to need
# apiextensions.k8s.io, traefik.containo.us, traefik.io
serviceAccount:
  # -- Create service account. Needed for managed outposts
  create: false  # doesn't work on NERC-OCP because

geoip:
  # -- enable GeoIP sidecars for the authentik server and worker pods
  enabled: true
  editionIds: "GeoLite2-City GeoLite2-ASN"
  # -- GeoIP update frequency, in hours
  updateInterval: 24
  ## use existing secret instead of values above
  existingSecret:
    # -- name of an existing secret to use instead of values above
    secretName: "maxmind-license"
    # -- key in the secret containing the account ID
    accountId: "account-id"
    # -- key in the secret containing the license key
    licenseKey: "license-key"

# Ref: https://github.com/bitnami/charts/blob/postgresql/12.12.10/bitnami/postgresql/README.md
postgresql:
  enabled: true
  architecture: standalone
  auth:
    username: authentik
    database: authentik
    existingSecret: trial-authentik-db-passwords
  primary:
    resources:
      requests: &POSTGRES_RESOURCES
        memory: 2Gi
        cpu: 500m
      limits: *POSTGRES_RESOURCES
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: true
      storageClass: ocs-external-storagecluster-ceph-rbd
      size: 4Gi
  backup:
    enabled: true
    cronjob:
      schedule: "@daily"
      concurrencyPolicy: ""
      failedJobsHistoryLimit: 2
      successfulJobsHistoryLimit: 2
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        runAsUser: null
        runAsGroup: null

# Ref: https://github.com/bitnami/charts/blob/redis/18.6.1/bitnami/redis/README.md
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: ocs-external-storagecluster-ceph-rbd
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

