authentik:
  error_reporting:
    # Opt-in to error and anonymous performance data reporting to sentry.io.
    # Authentik is an honest open-source company, we're doing our part to help!
    enabled: true

server:
  resources:
    requests: &REQUESTS
      cpu: 500m
      memory: 2Gi
    limits: *REQUESTS

  ingress:
    enabled: true
    ingressClassName: openshift-default
    annotations:
      cert-manager.io/issuer: letsencrypt
      acme.cert-manager.io/http01-ingress-class: openshift-default
    hosts: &HOSTS
      - auth.blt.chrisproject.org
    tls:
      - secretName: auth-blt-chrisproject-org-letsencrypt
        hosts: *HOSTS

serviceAccount:
  # -- Create service account. Needed for managed outposts
  create: true
  clusterRole:
    # -- Create a clusterole in addition to a namespaced role.
    enabled: false
  fullnameOverride: authentik

geoip:
  # -- enable GeoIP sidecars for the authentik server and worker pods
  enabled: true
  editionIds: "GeoLite2-City GeoLite2-ASN"
  # -- GeoIP update frequency, in hours
  updateInterval: 48
  ## use existing secret instead of values above
  existingSecret:
    # -- name of an existing secret to use instead of values above
    secretName: "maxmind-license"
    # -- key in the secret containing the account ID
    accountId: "account-id"
    # -- key in the secret containing the license key
    licenseKey: "license-key"

postgresql:
  # subchart very outdated, so we use our own.
  enabled: false

redis:
  # subchart very outdated, so we use our own.
  enabled: false
