global:
  defaultStorageClass: 'ocs-external-storagecluster-ceph-rbd'

  imagePullSecret:
    - name: fnndscnercpull  # DockerHub login for increased rate-limit

ingress:
  enabled: true
  className: openshift-default
  annotations:
    cert-manager.io/issuer: letsencrypt
    acme.cert-manager.io/http01-ingress-class: openshift-default
  hosts:
    - host: cube.blt.chrisproject.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cube-blt-chrisproject-org-letsencrypt
      hosts:
        - cube.blt.chrisproject.org

# OpenShift route
route:
  enabled: false

# ChRIS Backend
#####################
cube:
  image:
    repository: ghcr.io/fnndsc/cube
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # Use inter-pod affinity as a workaround for using a ReadWriteOnce PersistentVolumeClaim
  enablePodAffinityWorkaround: true

  # Prefix to use for job names submitted to Kubernetes. Ideally, this should be unique for each CUBE instance.
  # The default behavior is to use the release name as the job prefix.
  # jobPrefix: ""

  # Configuration
  #####################
  config:
    # smaller values increases responsiveness at the cost of resource usage and possibly concurrency bugs
    CUBE_CELERY_POLL_INTERVAL: "10.0"
    # HTTP server security settings
    DJANGO_ALLOWED_HOSTS: "*"  # note: * is okay if OpenShift router or k8s igress is validating host header
    DJANGO_CORS_ALLOW_ALL_ORIGINS: "false"
    DJANGO_CORS_ALLOWED_ORIGINS: "https://blt.chrisproject.org"
    DJANGO_SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
    DJANGO_USE_X_FORWARDED_HOST: "true"
    DISABLE_USER_ACCOUNT_CREATION: "true"
    AUTH_LDAP: "true"
    AUTH_LDAP_SERVER_URI: "ldap://ak-outpost-ldap:389"
    AUTH_LDAP_BIND_DN: "cn=ldapservice,ou=users,dc=blt,dc=chrisproject,dc=org"
    AUTH_LDAP_USER_SEARCH_ROOT: "ou=users,dc=blt,dc=chrisproject,dc=org"
    AUTH_LDAP_GROUP_SEARCH_ROOT: "dc=blt,dc=chrisproject,dc=org"
    AUTH_LDAP_CHRIS_ADMIN_GROUP: chris-admin

    AUTH_LDAP_USER_SEARCH_FILTER: '(cn=%(user)s)'  # Authentik usernames are exposed as cn
    AUTH_LDAP_USER_FLAGS_BY_GROUP: ''  # workaround for https://github.com/goauthentik/authentik/issues/7522#issuecomment-2525303023


  # Set of default plugins to register with the coupled pfcon (if .pfcon.enabled)
  # Plugins which CUBE is hard-coded to depend on should be listed here.
  # To add plugins for general use, see https://chrisproject.org/docs/tutorials/upload_plugin
  plugins:
    - https://cube.chrisproject.org/api/v1/plugins/1/   # pl-dircopy
    - https://cube.chrisproject.org/api/v1/plugins/2/   # pl-tsdircopy
    - https://cube.chrisproject.org/api/v1/plugins/3/   # pl-topologicalcopy

  storage:
    # In the default configuration, the volume is managed by pfcon's subchart, so leave this as "enabled: false"
    enabled: false

  # -- Main celery worker configuration.
  workerMains:
    # -- Resources for the main worker.
    # -- If an out-of-network pfcon is configured, memory allocation must be **at least**
    # -- twice as large as the largest anticipated plugin instance output directory's
    # -- total size. This is because of an inefficient implementation.
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 1

  workerPeriodic:
    ## Resources for the periodic worker.
    ## Default values should be okay. Memory request may be further reduced to ~400Mi.
    resources:
      requests:
        memory: 1Gi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 250m

  # -- CUBE ASGI server configuration.
  server:
    # -- CUBE server pod annotations.
    podAnnotations: {}
    # -- Deployment replicas count.
    replicas: 1
    # -- Service configuration.
    service:
      type: ClusterIP
      port: 8000
      # -- CUBE server service nodePort
      nodePort:
      # -- nodePortHost does nothing. It is simply used to print the URL of CUBE in the NOTES
      nodePortHost:

    # -- Resources for the HTTP server (ASGI).
    # -- Default values should be okay. About 256Mi of memory is needed per idle worker.
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 1

    # -- CUBE server container hostPort.
    hostPort:

# [SUBCHART] PostgreSQL packaged by Bitnami
# https://github.com/bitnami/charts/tree/main/bitnami/postgresql#parameters
postgresql:
  enabled: true
  auth:
    database: "chris"
    username: "chris"
  # one of: [standalone, replication]
  architecture: standalone
  primary:
    resources:
      requests:
        memory: 4Gi
        cpu: 1
      limits:
        memory: 4Gi
        cpu: 1
    persistence:
      enabled: true
      size: 8Gi

# [SUBCHART] RabbitMQ packaged by Bitnami
# https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq#parameters
rabbitmq:
  resourcesPreset: medium
  persistence:
    enabled: true
    size: 1Gi
  serviceBindings:
    enabled: true  # required

# -- Configuration of NATS, a messaging system. In ChRIS, NATS is used for PACS retrieve
# -- progress messages sent from oxidicom to CUBE.
# -- Documentation: https://github.com/bitnami/charts/tree/nats/8.4.3/bitnami/nats
nats:
  resourcesPreset: small
  podLabels:
    app.kubernetes.io/part-of: chris
  auth:
    # -- CUBE does not support NATS authorization
    enabled: false

# -- Configuration of pfcon, the ChRIS compute controller
pfcon:
  enabled: true

  name: "NERC-OCP"
  description: "NERC-OCP compute resource"
  replicaCount: 1
  podAnnotations: {}
  podSecurityContext: {}

  service:
    type: ClusterIP
    port: 5005

  nodeSelector: {}

  # -- Storage space for CUBE files should be configured here.
  # -- It is recommended to allocate as much space as possible for CUBE files.
  storage:
    existingClaim: ""
    size: 32Gi
    accessModes: [ "ReadWriteOnce" ]

  pfcon:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 384Mi

    # -- pfcon configuration
    # -- Recommended to keep as-is
    config:
      innetwork: true
      storageEnv: fslink

    # -- Extra environment variables.
    extraEnv:
      GUNICORN_CMD_ARGS: "--workers=4 --timeout=3600"

  pman:
    # It is unnecessary to increase pman's resources to above the minimum because
    # pman doesn't do anything besides sending and receiving HTTP requests.
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi

    workers: 4
    workerTimeout: 30

    # pman configuration
    # https://github.com/fnndsc/pman#environment-variables
    # SECRET_KEY, CONTAINER_ENV, STORAGE_TYPE, VOLUME_NAME, and CONTAINER_USER are handled automatically
    config:
      JOB_LABELS: chrisproject.org/job=plugininstance,chrisproject.org/instance=blt
      ENABLE_HOME_WORKAROUND: "yes"
      REMOVE_JOBS: "yes"
      IGNORE_LIMITS: "no"

# -- Configuration of PFDCM, the ChRIS PACS bridge
pfdcm:
  # -- Enable PFDCM, the ChRIS PACS bridge
  enabled: true

  # -- Extra environment variables for the PFDCM container.
  # -- Note: PORT is configured automatically, it is not recommended to set it manually.
  extraEnv:
    # -- Maximum number of web server workers.
    MAX_WORKERS: 4

  # -- Image for PFDCM
  image:
    repository: ghcr.io/fnndsc/pfdcm
    pullPolicy: IfNotPresent
    tag: "3.1.22"

  # -- DICOM application entity title
  aet: "BLT-ChRIS"

  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

  livenessProbe:
    httpGet:
      path: /api/v1/about/
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  # Kind configuration
  #####################
  # -- kind must be one of:
  # --
  # -- - "Deployment": use (standard) Kubernetes Deployment and Service APIs
  # -- - "Service": use the KNative Serving API
  kind: Service

  # KNative Serving configuration
  #####################
  # -- KNative Serving revision annotations.
  # -- Only used with `pfdcm.kind=Service`
  revisionAnnotations:
    autoscaling.knative.dev/target: "4"
    # autoscaling.knative.dev/min-scale: "1"
    # autoscaling.knative.dev/max-scale: "3"
    # autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m5s"

  # -- DICOM listener for pfdcm. Enabled when pfdcm is enabled.
  listener:
    image:
      repository: ghcr.io/fnndsc/oxidicom
      pullPolicy: Always
      tag: "pr-3"  # pre-alpha, has known bugs.

    replicas: 1

    ## manual configuration of OpenTelemetry
    # env:
    #   - name: OTEL_RESOURCE_ATTRIBUTES
    #     value: service.name=oxidicom
    #   - name: OTEL_EXPORTER_OTLP_ENDPOINT
    #     value: http://tempo:4317

    # -- Optional configurations of oxidicom.
    config:
      # -- number of DICOM listener threads
      # -- ref: https://chrisproject.org/docs/oxidicom/deployment#performance-tuning
      listenerThreads: 8

      # -- number of Tokio runtime threads
      # -- ref: https://chrisproject.org/docs/oxidicom/deployment#performance-tuning
      tokioThreads: 4

      # -- enable/disable logging and set verbosity of components
      logging: oxidicom=warn

      ## strictPduLength, uncompressedOnly, and maxPduLength are strange DICOM
      ## options which you probably want to leave as their default values.
      # strictPduLength: true
      # uncompressedOnly: true
      # maxPduLength: 16384
      ## Whether to accept unknown DICOM transfer syntaxes.
      # promiscuous: true

    resources:
      # It's written in Rust!
      # Memory usage typically stays under 20MiB, unless there is backpressure
      # from slow disk write speed
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi

orthanc:
  enabled: true
  imagePullSecrets:
    - name: fnndscnercpull
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 3Gi
  config:
    # The logical name of this instance of Orthanc. This one is
    # displayed in Orthanc Explorer and at the URI "/system".
    name: "BLT Orthanc v1"
    # Enable the transparent compression of the DICOM instances
    storageCompression: false
    # Action to take when the maximum storage is reached.
    # By default, the patients are recycled ("Recycle" mode).
    # In "Reject" mode, the sender will receive a 0xA700 DIMSE status code
    # if the instance was sent through C-Store, a 507 HTTP status code
    # if using the REST API and a 0xA700 Failure reason when using
    # DicomWeb Stow-RS 
    # Allowed values: "Recycle", "Reject"
    # (new in Orthanc 1.11.2)
    maximumStorageMode: Reject
    # Maximum size of the storage cache in MB.  The storage cache
    # is stored in RAM and contains a copy of recently accessed
    # files (written or read).  A value of "0" indicates the cache
    # is disabled.  (new in Orthanc 1.10.0)
    maximumStorageCacheSize: 0

    # The DICOM Application Entity Title
    dicomAet: "BLT-ORTHANC"
    # Check whether the called AET corresponds during a DICOM request
    dicomCheckCalledAet: false

    # The default encoding that is assumed for DICOM files without
    # "SpecificCharacterSet" DICOM tag, and that is used when answering
    # C-Find requests (including worklists). The allowed values are
    # "Ascii", "Utf8", "Latin1", "Latin2", "Latin3", "Latin4",
    # "Latin5", "Cyrillic", "Windows1251", "Arabic", "Greek", "Hebrew",
    # "Thai", "Japanese", and "Chinese".
    defaultEncoding: "Latin1"

    # Set the timeout (in seconds) after which the DICOM associations
    # are closed by the Orthanc SCP (server) if no further DIMSE
    # command is received from the SCU (client).
    dicomScpTimeout: 30

    # The timeout (in seconds) after which the DICOM associations are
    # considered as closed by the Orthanc SCU (client) if the remote
    # DICOM SCP (server) does not answer.
    dicomScuTimeout: 10

    # Whether or not the password protection is enabled
    authenticationEnabled: true

    # The list of the registered users. Because Orthanc uses HTTP
    # Basic Authentication, the passwords are stored as plain text.
    registeredUsers: {}

    # The list of the known DICOM modalities
    #
    # A fourth parameter is available to enable patches for a
    # specific PACS manufacturer. The allowed values are currently
    # "Generic" (default value), "StoreScp" (storescp tool from
    # DCMTK), "ClearCanvas", "MedInria", "Dcm4Chee", "SyngoVia",
    # "AgfaImpax" (Agfa IMPAX), "EFilm2" (eFilm version 2), and
    # "Vitrea". This parameter is case-sensitive.
    dicomModalities:
      # !!!IMPORTANT!!!
      # To use in combination with pfdcm, you MUST define a modality for
      # `.Values.pfdcm.aet`
      "BLT-ChRIS": [ "BLT-ChRIS", "chris-oxidicom", 11111 ]

    # Whether Orthanc monitors its metrics (new in Orthanc 1.5.4). If
    # set to "true", the metrics can be retrieved at
    # "/tools/metrics-prometheus" formetted using the Prometheus
    # text-based exposition format.
    metricsEnabled: false

  ohif:
    enabled: true
    # BTW, it's impossible to configure Orthanc's OHIF to connect with pfdcm-dicomweb.

    # OHIF custom config file
    # https://orthanc.uclouvain.be/book/plugins/ohif.html#user-configuration-of-ohif
    # userConfiguration: |
    #   window.config = {
    #     extensions: [],
    #     modes: []
    #   }

  persistence:
    storage:
      size: 8Gi
      storageClass: ocs-external-storagecluster-ceph-rbd
      accessModes: [ ReadWriteOnce ]
    index:
      size: 1Gi
      storageClass: ocs-external-storagecluster-ceph-rbd
      accessModes: [ ReadWriteOnce ]
