repositories:
  - name: fnndsc
    url: https://fnndsc.github.io/charts

helmDefaults:
  createNamespace: false
  diffArgs: [ --dry-run=server ]

releases:
    # This instance is currently broken because NooBaa is broken.
    # Support ticket: https://mghpcc.supportsystem.com/tickets.php?id=16908
    # We are keeping it alive for troubleshooting.
  - name: orthanc
    chart: fnndsc/orthanc
    version: 2.0.0
    values:
      - global:
          imagePullSecrets:
            - name: fnndscnercpull
        config:
          Name: Boston-London-Toronto
          HttpsVerifyPeers: false  # TODO does this make NooBaa work?
          HttpsCACertificates: ""
          HttpVerbose: true
          DeidentifyLogs: false
          StorageCompression: false
          AwsS3Storage:
            EnableAwsSdkLogs: true
            StorageEncryption:
              Enable: true
              MasterKey: "auto"
          DicomAet: BLT-ORTHANC
          DicomModalities:
            "BLT-ChRIS": [ "BLT-ChRIS", "chris-oxidicom", 11111 ]
        resources:
          requests: &REQUESTS
            cpu: 1
            memory: 4Gi
          limits: *REQUESTS
        crunchyPgo:
          enabled: true
          spec:
            instances:
              - dataVolumeClaimSpec:
                  accessModes: [ ReadWriteOncePod ]
                  resources:
                    requests:
                      storage: 1Gi
                  storageClassName:
                name: instance1
                replicas: 1
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 250m
                    memory: 256Mi
        objectStorage:
          enabled: true
          forceHttp: true
        oauth2-proxy:
          enabled: false
