apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: hosting-of-medical-image-analysis-platform-dcb83b
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-key  # must be something unique
    solvers:
      - http01:
          ingress:
            class: openshift-default
            podTemplate:
              spec:
                resources:
                  requests:
                    cpu: 25m
                  limits:
                    cpu: 100m
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    email: dev@babymri.org
