# https://artifacthub.io/packages/helm/bitnami/mongodb

clusterDomain: cluster.local

architecture: standalone
useStatefulSet: false
auth:
  enabled: false
tls:
  enabled: false

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi

containerPorts:
  mongodb: 27017

persistence:
  enabled: true
  storageClass: "ocs-external-storagecluster-ceph-rbd"
  accessModes: [ "ReadWriteOnce" ]
  size: 8Gi
  annotations: {}

volumePermissions:
  enabled: false

arbiter:
  enabled: false

metrics:
  enabled: false
