kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fetalmri
  labels:
    app.kubernetes.io/name: cube-fetalmri-org
spec:
  to:
    kind: Service
    name: cube-fetalmri-org-server
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    destinationCACertificate: ''
  port:
    targetPort: http
  host: fetalmri-cube.apps.shift.nerc.mghpcc.org
