kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: acpo-pfcon
  labels:
    app.kubernetes.io/name: pfcon
    app.kubernetes.io/instance: acpo-only
spec:
  to:
    kind: Service
    name: acpo-only-pfcon
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    destinationCACertificate: ''
  port:
    targetPort: http
