# Default values for ohif.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/ohif/app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podAnnotations:
  kubernetes.io/description: "Open Health Imaging Foundation DICOM viewer"
podLabels: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: openshift-default
  annotations:
    cert-manager.io/issuer: letsencrypt
    acme.cert-manager.io/http01-ingress-class: openshift-default
  hosts:
    - host: ohif.chrisproject.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ohif-chrisproject-org-letsencrypt
      hosts:
        - ohif.chrisproject.org

config:
  routerBasename: "/"
  extensions: []
  modes: []
  showStudyList: true
  defaultDataSourceName: "pfdcm1"
  dataSources:
    - namespace: "@ohif/extension-default.dataSourcesModule.dicomweb"
      sourceName: "pfdcm1"
      configuration:
        friendlyName: "PFDCM1 on NERC"
        name: "pfdcm1"
        wadoUriRoot: "https://pfdcm1-dicomweb.apps.shift.nerc.mghpcc.org/dicomweb"
        qidoRoot: "https://pfdcm1-dicomweb.apps.shift.nerc.mghpcc.org/dicomweb"
        wadoRoot: "https://pfdcm1-dicomweb.apps.shift.nerc.mghpcc.org/dicomweb"
        qidoSupportsIncludeField: false
        supportsReject: false
        imageRendering: wadors
        thumbnailRendering: wadors
        enableStudyLazyLoad: true
        supportsFuzzyMatching: false
        supportsWildcard: false
        staticWado: false
        singlepart: "bulkdata,video"
        bulkDataURI:
          enabled: true
          relativeResolution: studies
        omitQuotationForMultipartRequest: true
    # whiteLabeling: "{}"

resources:
  limits:
    cpu: 500m
    memory: 1907Mi
  requests:
    cpu: 500m
    memory: 1907Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
