kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: blt-orthanc
  annotations:
    kubernetes.io/description: "Installs custom plugins into Orthanc."
spec:
  runPolicy: Serial
  triggers:
    - type: ConfigChange
  source:
    dockerfile: |
      # syntax=docker/dockerfile:1.2
      FROM jodogne/orthanc-plugins
      ARG RELEASE
      ADD --chmod=644 https://github.com/FNNDSC/orthanc-patient-list/releases/download/release%2F${RELEASE}/libpatient_list_ui.so /usr/local/share/orthanc/custom_plugins/libFnndscPatientList.so
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: docker.io/jodogne/orthanc-plugins:1.12.9
      pullSecret:
        name: fnndscnercpull
      buildArgs:
        - name: RELEASE
          value: "20250812"
  output:
    to:
      kind: ImageStreamTag
      name: orthanc:blt
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 2
  completionDeadlineSeconds: 600
