apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: psql
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker.io/alpine/psql:16.3
    name: "16.3"
    referencePolicy:
      type: Source
